project_name: unface

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

release:
  github:
    owner: schneid-l
    name: unface
  prerelease: auto
  draft: false

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Fixes
      regexp: '^fix'
      order: 1
    - title: Others
      order: 999
